---
- hosts: local

  tasks:
# already done by Dockerfile
#    - name: ensure apt cache is updated
#      action: apt update_cache=yes

    - name: ensure all software is installed
      action: apt name={{item}}
      with_items:
        - nginx